name: Test applicaiton

on: ["push", "pull_request"]

jobs:
  test:
    name: Test applicaiton
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          pip install --upgrade pip setuptools
          pip install .[all]
          pip install -r requirements.txt
          pip install pyyaml
          pip install --upgrade pytest pytest-cov telethon pytest-asyncio
      - name: Run tests
        run: pytest --cov-report=xml --cov=quizbot tests/
      - name: codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}